### ISSUE TITLE
TYPO3 CMS Core contribution welcome

### ISSUE THREAD

**Issue by liayn** [olegsv/typo3rtl#1]
Hi!

Would you like to participate in TYPO3 CMS Core development and add those changes directly to Core?
This way all users would benefit from your work and wouldn't need to install extra extensions.

If you're interested, get in touch with us on Slack.
http://typo3.org/support/community/

Kind regards
Markus

---

TYPO3 CMS Active Contributors Team Member
TYPO3 .... inspiring people to share!

**Comment by olegsv** [comment]
Dear Marcus,
Thank you for the invitation. 
I would be glad to help with incorporating RTL support into Typo3 core. I believe we're talking about 7.x branch? 

I 'm afraid I will need someone's help to get started with dev environment and all the tools. This and yes, I would be glad if thete is an up-to-date manual on backend specific topics. IRC channels are mixed bag when it comes to programming questions.

Of course, feel free to use my code and merge it into the core. 

With best regards,
Oleg Sverdlov

-----Original Message-----

**Comment by liayn** [comment]
Great to hear.
We are talking about master branch, which is the basis for the regular 7.x sprint releases and which will finally lead us to the 7 LTS version in autumn.

Regarding environment setup, http://wiki.typo3.org/CWT will give you a good start. If something is not clear in this guide, please get back to us/me (or improve directly).

We're not using the IRC channels anymore for Core development. Most communication is handled on Slack now. (https://forger.typo3.org/slack to get your account for free)
